name: superset
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  numberpicker: ^2.1.0
  http: ^1.2.1
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/i18n/
    - assets/language_options.json
    - assets/i18n/EN.json
    - assets/i18n/ES.json
  uses-material-design: true
